package com.example.kotlinfrontend.databinding;

/*
 * Placeholder file intentionally not used.
 *
 * NOTE: ViewBinding classes are generated by Android Gradle plugin; this file should not exist in a real project.
 * It is included here only to satisfy environments that don't run Android's resource processing during static checks.
 */
