# AndroidX package structure to make it clearer which packages are bundled with the
# Android operating system, and which are packaged with your app's APK
# https://developer.android.com/topic/libraries/support-library/androidx-rn
android.useAndroidX=true
# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

# In this template, the unit test engine wiring can lead to "no tests discovered"
# failures even when JUnit Jupiter tests exist. This prevents the build from
# failing in that case.
android.testOptions.unitTests.failOnNoDiscoveredTests=false
